export const  QUESTIONS=[
    "What is your favourite quote?",
    "Speed or Accuracy- What do you believe is more important while undertaking a task?",
    "If you could do it all over again, would you change anything?",
    "Can enemies ever become friends?",
    "Are leaders born or made?",
    "What will you never give up on?",
    "What do you usually think about on your drive home from work?",
    "What do you owe yourself?",
    "Do you think intelligence is fixed or can anyone become smarter with desire?",
    "When you think of home, what specifically do you think of?",
    "If animals could talk, which animal would be the funniest?",
    "What's the best way to spend a rainy day?",
    "What was your favorite thing to do as a child that you would love to still be able to do as an adult?",
    "What has life taught you recently?",
    "Would you ever go sky diving, why or why not?",
    "What's the most important step to calm down a person who is angry?",
    " Which is worse, failing or never trying?",
    "What is the most desirable trait another person can possess?",
    "“What is your favorite quote from a book and how does it inspire you?”",
    "When did you not speak up when you should have?",
    "If not now, then when?",
    "What is something you've always wanted to try but have been too afraid to?",
    "Should everyone write at least 1 book in their life?    ",
    "What do you imagine yourself doing ten years from now?",
    "Do you ever celebrate the green lights?",
    "What is your number one goal for the next six months?",
    "How do you spend the majority of your free time?",
    "If you could have any superpower, what would it be?",
    "What is the most daring thing you've ever done?",
    "What role does music play in your life?",
    "What was your favorite childhood toy? ",
    " Are you more worried about doing things right, or doing the right things?",
    "What is the difference between innocence and ignorance?",
    "What small act of kindness were you once shown that you will never forget?",
    "What's your definition of happiness?",
    "What do you think are the most important qualities for success?",
    "Describe a moment that changed your life forever. ",
    "Do you think people can change, why or why not?",
    "How important is creativity in your personal and professional life?",
    "Should adults read fiction, why or why not?",
    "Which person inspires you and why?",
    "What stresses you out?",
    "Do you think charities do more harm than good?",
    "What makes someone a hero?",
    "What's one downside of the modern day world?",
    "What bad habits do you want to break?",
    "What type of person angers you the most?",
    "When you have a random hour of free time, what do you usually do?",
    "Does travelling broaden a persons mind?",
    "Where do you find peace?",
    "What was your favorite thing to do as a child that you would love to still be able to do as an adult?",
    "If you could go back in time and tell your younger self one thing, what would it be?",
    "What are your 3 favorite personality traits?",
    "You can have anyone fictional as your imaginary friend. Who do you choose and why?",
    "Beyond the titles that others have given you, who are you?",
    "Do you believe in luck?",
    "What fictional world or place would you like to visit?",
    "What would be the title of your autobiography?",
    "Is it always wrong to lie? When,if ever, is it okay?",
]